### ISSUE TITLE
Feature: User can like NA teams

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User Can like NA LCS teams
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will view a list of NA LCS teams and be able to click on the team clickers to mark or unmark teams they want to like.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![user can like NA teams mobile](https://user-images.githubusercontent.com/116613246/211692714-a0cc9817-37e3-4c83-9e78-bfbc16e8c4c8.png)
![user can like NA teams desktop](https://user-images.githubusercontent.com/116613246/211692616-8123230f-59b3-46cf-b9ac-59016e699113.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create HTML Layout for top navbar.
  - [x] Make the Teams Button in Navbar link to the Teams page.
- [x] Setup layout of page with three rows for the H1, 10 team clickers, and selected teams button.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] For each button, Add a 'click' event listener that:
  - [x] changes the background-color of the selected icon:
    - [x] turns on when it was off.
    - [x] turns off when it was on. 
  - [x] stores the selected teams into the data model object if button is turned on
  - [x] removes selected teams in the data model object if button is turned off
- [x] Add a `'submit'` event listener for the Teams page that:
  - [x] prevents the page from refreshing when the form is submitted.
  - [x] copies the selected teams in the data model object into the stored teams data model object.
- [x] In `data.js`, add a `'beforeunload'` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [x] At the bottom of `data.js`, include a conditional statement that:
  - [x] checks to see if there is a JSON data model stored in `localStorage`.
  - [x] if there is, parse it and assign it to the initial `data` variable so that the user can view their previous instance after load from the pre-existing data model.
- [x] Test the app by selecting and submitting teams and then reloading the page to confirm that:
  - [x] the data model is being saved to `localStorage` before each page reload.
  - [x] the data model stores the selected teams and is stored if the submit button was clicked
- [x] Make DOM Tree based off of API data.
- [x] Add a teams nav bar only open for desktop sizes
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
