### ISSUE TITLE
Feature: User can view standings of teams

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view standings of teams and swap between choosing their teams and seeing their standings.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to view page after previous page submits and will see page for team standings.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![User can view team standings - Mobile](https://user-images.githubusercontent.com/116613246/211873176-596ef3d7-64d4-4c45-bf03-652d6495f7e1.png)
![User can view team standings - Desktop](https://user-images.githubusercontent.com/116613246/211873409-cd2be7a5-74ac-4886-af81-75e9001cd931.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a new tab for the new page of Standings
- [x] Set the layout for the standings page with:
  - [x] mobile layout set up first and moving seamlessly to desktop. 
  - [x] A top and bottom border for each item.
  - [x] The standing, a logo, name and the score per team
  - [x] grab information for usage from api.
- [x] Incorporate a view-swap by:
  - [x] setting the current view page as a variable logged into the data model.
  - [x] having JavaScript have other pages as hidden
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
