### ISSUE TITLE
Feature: User can view roster of chosen team

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view rosters of teams by clicking on the teams in the standings page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the standings page, the user will click on a team's standings to view more information regarding the roster of the chosen team.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![User can view roster of chosen team Desktop](https://user-images.githubusercontent.com/116613246/212137206-d1254605-b2d5-46a0-813b-b49b2e7da329.png)
![User can view roster of chosen team Mobile](https://user-images.githubusercontent.com/116613246/212137344-14844e8d-c338-4803-8121-840f37eb36bb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Set the layout for the standings page with:
  - [x] mobile layout set up first and moving seamlessly to desktop. 
  - [x] add image of team and according name for title.
  - [x] A top and bottom border for each player.
  - [x] The role, player name and player image.
  - [x] order first off top, jungle, mid, bottom, support
  - [x] grab information for usage from api.
    - [x] for amount of players after main 5 roles, run loop through to incorporate into roster page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
