### ISSUE TITLE
Feature: User can view ongoing tournaments and schedules

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view ongoing tournaments and schedules.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

With the user being able to choose their teams from the previous pages, this page will show the standings in chronological order of the whole tournament and hold another tab that only includes the liked teams.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/116613246/213324578-da59d3db-817c-4d59-b6bd-da64cd6f8645.png)
![image](https://user-images.githubusercontent.com/116613246/213324429-f2716f3d-26c5-438e-bfc2-ff8578c1da5b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
 Set the layout for the standings page with:
mobile layout set up first and moving seamlessly to desktop.
add image of team and according name for title.

- [x] Set the layout for the standings page with:
  - [x] mobile layout set up first and moving seamlessly to desktop.
  - [x] layout the standings to look like the figma where date and opposing teams data acquired from API.
  - [x] grab information for usage from API regards to schedules.
- [x] Set teams page information to update based on which teams are stored in JSON data model.
- [x] have the changing submission of teams stored to change the output of liked teams.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
